import type { Metadata } from "next";
import localFont from "next/font/local";

import { Providers } from "./providers";
import "./globals.css";

import Header from "@/layouts/Header/main";
import Footer from "@/layouts/Footer/main";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Billiards App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="w-full min-h-screen bg-backgroundContainer-color flex flex-col items-center justify-center space-y-16 ">
            <Header />
            <div className="xl:pt-[180px] w-full min-h-screen flex flex-col items-center pointer-events-auto">
              {children}
            </div>
            <Footer />
          </div>

        </Providers>
      </body>
    </html>
  );
}
